name: 🚀 Release
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - beta
      - "*.x"
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      # install semantic-release plugins
      - run: npm install --no-save semantic-release-plugin-github-breaking-version-tag
      # build and package
      - run: npm run build-and-package
      # configure git to push commit back to release branch with build
      - run: |
          git config user.name "Evan Bonsignori"
          git config user.email "evanabonsignori@gmail.com"
      # do the release
      - run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
