name: 🚀 Release
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - beta
      - "*.x"
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: npm
      # install semantic-release plugins
      - run: npm install --no-save semantic-release-plugin-github-breaking-version-tag
      # configure git to push commit back to release branch with build
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm run build 
          npm run package
          LAST_MESSAGE=$(git log -1 HEAD --pretty=format:%s)
          git add --all
          git diff --quiet && git diff --staged --quiet || git reset --soft HEAD~1 && git add --all && git commit -a -m $LAST_MESSAGE && git push --force
      # do the release
      - run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
